# Theme (use academicpages as a remote theme)
locale                   : "en-US"
site_theme: "air"
title: "Zhiruo (Rachel) Zhang"
name: &name "Zhiruo (Rachel) Zhang"
description: &description "Ph.D. Candidate in Economics and Econometrics at The University of Adelaide"
repository: "zhiruozzr/zhiruozzr.github.io"

author:
  avatar    : "images/profile.jpg"
  name      : "Zhiruo (Rachel) Zhang 张芷若"
  bio       : "Ph.D. Candidate in Economics and Econometrics at The University of Adelaide"
  location  : "Adelaide, Australia"
  email     : "zhiruo.zhang@adelaide.edu.au"
  github    : "zhiruozzr"
  linkedin  : "https://www.linkedin.com/in/zhiruo-zhang-016b86179/"
  orcid     : "https://orcid.org/0000-0002-4887-3068"

# Enable top nav bar
header_pages:
  - _pages/research.md
  - _pages/cv.md
  - _pages/teaching.md
#  - _pages/contact.md
  
# Directory settings
include:
  - _pages
  - files
  - images
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README
  - Rakefile
  - package.json
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - assets/js/vendor
  - tmp
  - log

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Permalinks & Timezone
timezone: Australia/Adelaide
permalink: /:categories/:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins (GitHub Pages allowlisted)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
