title: "Zhiruo (Rachel) Zhang"
name: &name "Zhiruo (Rachel) Zhang"
description: &description "Ph.D. Candidate in Economics and Econometrics at The University of Adelaide"
repository: "zhiruozzr/zhiruozzr.github.io"

# Author Info
author:
  avatar    : "images/IMG_1514.JPG"
  name      : "Zhiruo (Rachel) Zhang (张芷若)"
  bio       : *description
  location  : "Adelaide, Australia"
  employer  : "The University of Adelaide"
  email     : "zhiruo.zhang@adelaide.edu.au"
  github    : "zhiruozzr"
  linkedin  : "https://www.linkedin.com/in/zhiruo-zhang-016b86179/"
  orcid     : "https://orcid.org/0000-0002-4887-3068"

# Build settings
remote_theme: academicpages/academicpages.github.io
markdown: kramdown
highlighter: rouge

# Markdown options
kramdown:
  input: GFM

# Directory settings
include:
  - _pages
  - files

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README
  - Rakefile
  - package.json
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - assets/js/vendor
  - tmp
  - log

# Timezone and Permalink
timezone: Australia/Adelaide
permalink: /:categories/:title/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
