title: "Zhiruo (Rachel) Zhang"
name: &name "Zhiruo (Rachel) Zhang"
description: &description "Ph.D. Candidate in Economics and Econometrics at The University of Adelaide"
repository: "zhiruozzr/zhiruozzr"

# Author Info
author:
  avatar    : "images/IMG_1514.JPG"
  name      : "Zhiruo (Rachel) Zhang (张芷若)"
  bio       : *description
  location  : "Adelaide, Australia"
  employer  : "The University of Adelaide"
  email     : "zhiruo.zhang@adelaide.edu.au"
  github    : "zhiruozzr"
  linkedin  : "https://www.linkedin.com/in/zhiruo-zhang-016b86179/"
  orcid     : "https://orcid.org/0000-0002-4887-3068"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Markdown options
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Directory settings
include:
  - _pages
  - files

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README
  - Rakefile
  - package.json
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - assets/js/vendor
  - tmp
  - log
  - google_scholar_crawler
  - github_myprofile_updater

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks & Timezone
permalink: /:categories/:title/
timezone: Australia/Adelaide

# Layout defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins (GitHub Pages safe list)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate

# Whitelist for GitHub Pages safe mode
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
