name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'  # Executes every 12 hours, corrected cron syntax
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate Snake Game based on GitHub Contributions
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: zzhrachel
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
